services:
  - type: web
    name: attendance-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    pythonVersion: 3.11.8
